### ISSUE TITLE
Greater/less than operator currently not working on dates

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesforce#41]
Repro Steps:
1. Run the yml file

```yml
scenario: SalesForce Opportunity Test
description: This test the Opportunity creation and validation of field in SalesForce.

tokens:
  test:
    name: TestOnly
    closedate: 2020-09-08
    leadsource: Other
    stagename: Prospect
    probability: 20

steps:
- step: Create a salesforce opportunity
  data:
    opportunity:
       Name: '{{test.name}}'
       CloseDate: '{{test.closedate}}'
       LeadSource: '{{test.leadsource}}'
       StageName: '{{test.stagename}}'
       Probability: '{{test.probability}}'

- step: Validate that the Name field on salesforce opportunity with Name {{test.name}} should contain Test
- step: Validate that the Name field on salesforce opportunity with Name {{test.name}} should be {{test.name}}
- step: Validate that the StageName field on salesforce opportunity with Name {{test.name}} should not be Unknown
- step: Validate that the AccountId field on salesforce opportunity with Name {{test.name}} should not be 0010b00002TkPi9AAF
- step: Validate that the StageName field on salesforce opportunity with Name {{test.name}} should contain pect
- step: Validate that the CloseDate field on salesforce opportunity with Name {{test.name}} should be greater than 2019-09-08
- step: Validate that the LeadSource field on salesforce opportunity with Name {{test.name}} should be {{test.leadsource}}
- step: Validate that the Probability field on salesforce opportunity with Name {{test.name}} should be less than 10
- step: Delete the salesforce opportunity with Name {{test.name}}
```

Expected Result:
Less than/Greater than operator should be used on dates
