### ISSUE TITLE
Campaign Member Test is failing when using "not set to" operator

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesforce#42]
**Repro Steps:**
1. Run the yml file below
```yml
scenario: SalesForce Campaign Member Smooth Operator Test
description: This test the creation of Lead in Web and validation of campaign member fields in SalesForce. 

tokens:
  testEmail: jgeronimo@thisisjust.atomatest.com
  testLastname: John
  testFirstname: Geronimo
  testCompany: YS Corp
  testSubmit: button[type=submit]

steps:
- step: Navigate to http://go.automatoninc.com/Developer_Success.html
- step: Fill out input[id=FirstName] with {{testFirstname}}
- step: Fill out input[id=LastName] with {{testLastname}}
- step: Fill out input[id=Email] with {{testEmail}}
- step: Fill out input[id=Company] with {{testCompany}}
- step: Submit the form by clicking {{testSubmit}} 
- waitFor: 300
  step: Validate that the salesforce lead {{testEmail}} should have campaign member Status set to Success on campaign 7010b000001Ej51
- step: Validate that the salesforce lead {{testEmail}} should be a member of campaign 7010b000001Ej51
- step: Validate that the salesforce lead {{testEmail}} should have campaign member LastName containing Joh on campaign 7010b000001Ej51
- step: Validate that the salesforce lead {{testEmail}} should have campaign member Email not set to google.com on campaign 7010b000001Ej51
- step: Delete the {{testEmail}} Marketo lead
- step: Delete the {{testEmail}} Salesforce lead
```

![image](https://user-images.githubusercontent.com/54615569/69867170-050e8280-12e1-11ea-992f-a18dbeea83fd.png)

**Expected Result:**
"not" should not be part of the field field
