### ISSUE TITLE
Unclear test result message when less than/greater than operator is used in a numerical value/dates

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-salesforce#51]
Upon further investigation, this issue is happening when using the ff operators:

- be less than
- be greater than
- not be
- not contain

_**Note:
This is happening on all cogs.**_

**Repro Steps:**
Run the yml file

```yml
scenario: SalesForce Opportunity Test with operators
description: This test the smooth operators when creating Opportunity in SalesForce.

tokens:
  test:
    name: TestOnly
    closedate: 2020-08-09
    leadsource: Other
    stagename: Prospect
    probability: 20

steps:
- step: Create a salesforce opportunity
  data:
    opportunity:
       Name: '{{test.name}}'
       CloseDate: '{{test.closedate}}'
       LeadSource: '{{test.leadsource}}'
       StageName: '{{test.stagename}}'
       Probability: '{{test.probability}}'

- step: Validate that the Name field on salesforce opportunity with Name {{test.name}} should contain Test
- step: Validate that the Name field on salesforce opportunity with Name {{test.name}} should be {{test.name}}
- step: Validate that the StageName field on salesforce opportunity with Name {{test.name}} should not be Unknown
- step: Validate that the AccountId field on salesforce opportunity with Name {{test.name}} should not be 0010b00002TkPi9AAF
- step: Validate that the StageName field on salesforce opportunity with Name {{test.name}} should contain pect
- step: Validate that the CloseDate field on salesforce opportunity with Name {{test.name}} should be less than 2020-09-07
- step: Validate that the LeadSource field on salesforce opportunity with Name {{test.name}} should be {{test.leadsource}}
- step: Validate that the Probability field on salesforce opportunity with Name {{test.name}} should be less than 10
- step: Delete the salesforce opportunity with Name {{test.name}}

```
**Actual Result:**
![image](https://user-images.githubusercontent.com/54615569/70967673-e1fe1400-20d1-11ea-8c80-676c2437793c.png)
![image](https://user-images.githubusercontent.com/54615569/70975236-796c6280-20e4-11ea-8f44-091c92a56fe1.png)
![image](https://user-images.githubusercontent.com/54615569/70978155-34e3c580-20ea-11ea-8416-b940361a4a3d.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/54615569/70967613-b0854880-20d1-11ea-955f-6d06b4375862.png)
